### ISSUE TITLE
Support for board: xcvu9p-flgb2104-2-i

### ISSUE THREAD

**Issue by andylehti** [Ed-Yang/xilinx-ethash#1]
I've been trying my hand at creating an ethcoin miner but the source codes are so convoluted with other CPPs. So far, Vitis has not liked any of them that I try to build in it. I can build other software just fine. But for some reason, these keep failing.

**Comment by Ed-Yang** [comment]
I am not familiar with the xcvu9, this project using Vitis 2020.2/ and has been tested on Ubuntu 18.4.  

You can download the toolchains here: 

https://www.xilinx.com/products/boards-and-kits/alveo/u50.html#gettingStarted
