### ISSUE TITLE
help to use in vitis

### ISSUE THREAD

**Issue by RezaAhmadi0117** [Ed-Yang/xilinx-ethash#2]
hi, i wanna know is that possible to make xclbin file in vitis?
and how can i config files in vitis 2020.2.

**Comment by Ed-Yang** [comment]
I did not try to build it on Vitis IDE, maybe you can ask in Xilinx community: https://forums.xilinx.com

What do you mean "config files in vitis 2020.2" ?  If it means modify the items in "connectivity_u50.ini", you should check Xilinx manual.

**Comment by RezaAhmadi0117** [comment]
no, i just try to build your project in ide.

**Comment by Ed-Yang** [comment]
Jack has constructed a Vitis 2020.2 IDE project, you can find the zip file in discussion thread.

You have to register to check it out.

https://forums.xilinx.com/t5/Vitis-Acceleration-SDAccel-SDSoC/Run-ethash-OpenCL-kernel-on-Alveo-U50-PCIe-card-is-much-slower/m-p/1242387#M9222
